CREATE TABLE [dbo].[EX_TASK]
(
	[ID] INT NOT NULL IDENTITY, 
    [DESCRIPTION] NVARCHAR(256) NULL, 
    [NAME] NVARCHAR(50) NOT NULL, 
    [CREATION_DATE] DATETIME NOT NULL, 
    [COMPLETE_DATE] DATETIME NULL, 
    [CATEGORY_ID] INT NULL, 
    [STATUS_ID] INT NULL,

	CONSTRAINT [PK_EX_TASK] PRIMARY KEY ([ID]),
)
