CREATE TABLE EX_TASK
(
	ID 				NUMBER(11,0) 	NOT NULL, 
    DESCRIPTION		NVARCHAR2(256) 	NULL, 
    NAME 			NVARCHAR2(50) 	NOT NULL, 
    CREATION_DATE 	DATE 		    NOT NULL, 
    COMPLETE_DATE 	DATE 		    NULL, 
    CATEGORY_ID 	NUMBER(11,0) 	NULL, 
    STATUS_ID		NUMBER(11,0) 	NULL,

	CONSTRAINT PK_EX_TASK PRIMARY KEY (ID)
);
/
CREATE SEQUENCE SEQ_EX_TASK MINVALUE 1 START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER TRG_ID_EX_TASK
				BEFORE INSERT ON EX_TASK
				FOR EACH ROW
				BEGIN
				  :new.id := SEQ_EX_TASK.NEXTVAL;
				END;
/

DESC EX_TASK